services:
  member-service:
    build:
      context: ..
      dockerfile: member-service/Dockerfile
    container_name: member-service
    environment:
      - MEMBER_DB_USERNAME=${MEMBER_DB_USERNAME}
      - MEMBER_DB_PASSWORD=${MEMBER_DB_PASSWORD}
      - MEMBER_DB_NAME=${MEMBER_DB_NAME}
    ports:
      - "8090:8090"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8090/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - service-app-network
    restart: no

networks:
  service-app-network:
    driver: bridge